### ISSUE TITLE
TransactionalVersion in StateManagerImpl is null for versioned entites whitch are fetched eagerly by using relational annotation

### ISSUE THREAD

**Issue by AliasVector** [datanucleus/datanucleus-api-jpa#25] opened 2016-06-28 11:49 UTC
Hello.
We use datanucleus 4.2.5 jpa with jcache (on appengine).
Recently we face with a problem of updating relational object in our entities with enabled 2nd level cache (jcache in our case). 
We have the relation OneToOne for our entities: User - Address. Both of them have versioned field of Long type. During update we retrieve the User entity which has OneToOne Address entity which is fetched eagerly (default value for OneToOne mapping).
After updating fields of these entities on saving User we get the following exception:

"Caused by: org.datanucleus.exceptions.NucleusException: Object with id "1" in table address has no version set on the object in memory and you want to update it!! Please report this bug to the developers of DataNucleus with a way of reproducing it"

(The version value is set in database.)

After some investigation we found that the problem relates to the class StateManagerImpl the "transactionalVersion" field is not set for eagerly fetched entities. 

For User entity "transactionalVersion" is set as expected, but for Address entity - no. So we got the error at the line: 384 of UpdateRequest class in this code:
"if (currentVersion == null)
                            {
                                // Somehow the version is not set on this object (not read in ?) so report the bug
                                String msg = Localiser.msg("052201", op.getInternalObjectId(), table);
                                NucleusLogger.PERSISTENCE.error(msg);
                                throw new NucleusException(msg);
                            }
"

We also found that if we change the fetching type = lazy - the problem disappears.

**Comment by andyjefferson** [comment] 2016-06-28 12:39
I see no valid testcase ("way of reproducing it"). Refer to http://www.datanucleus.org/documentation/problem_reporting.html

**Comment by andyjefferson** [comment] 2016-07-03 06:30
Closing since no testcase provided. Attach a testcase here and it can be reopened

**Closed by andyjefferson** 2016-07-03 06:30 UTC
Labels: testcase_required
