### ISSUE TITLE
Converter column length

### ISSUE THREAD

**Issue by spassignat** [datanucleus/datanucleus-api-jpa#121] opened 2021-05-04 12:10 UTC
Hi,

Column length doesn't fully work with Converter.
```
@Convert(converter = AddressToStringConverter.class)
@Column(columnDefinition = "VARCHAR(4096)", length = 4096)
@Size(max = 4096)
private Address addressString;
```

ColumnMetadata is loaded properly and schema generation seem to work well, but write operation raises a validation error, the column length is still compared to the defaut value (255).

I can't find where this ColumnMetadata is created without length value.

Appears on DN 5.2.6

**Comment by spassignat** [comment] 2021-05-04 16:06
Converter column length #121 #20

**Comment by andyjefferson** [comment] 2021-05-04 17:19
A javax.validation error is based on what is being put into a field, not on any internal ColumnMetaData. 
If schema generation is correct then DataNucleus handling should be fine.
But then you'd need to post the actual exception and stack trace for people to see what the problem is.

**Comment by andyjefferson** [comment] 2021-06-08 07:10
No test present so closing.

**Closed by andyjefferson** 2021-06-08 07:10 UTC
Labels: testcase_required, unresourced
